### ISSUE TITLE
ert/ecllib dependency not checked.

### ISSUE THREAD

**Issue by blattms** [OPM/opm-parser#1074] opened 2017-06-06 10:18 UTC
CMake runs through on my Debian system with stand-alone opm-parser. I would assume that this means all dependencies are there. Well they are not:
```
[ 16%] Building CXX object lib/eclipse/CMakeFiles/opmparser.dir/Deck/Section.cpp.o
In file included from /tmp/opm-parser/lib/eclipse/include/opm/parser/eclipse/EclipseState/EclipseConfig.hpp:25:0,
                 from /tmp/opm-parser/lib/eclipse/include/opm/parser/eclipse/EclipseState/EclipseState.hpp:27,
                 from /tmp/opm-parser/lib/eclipse/include/opm/parser/eclipse/Parser/Parser.hpp:30,
                 from /tmp/opm-parser/lib/eclipse/Deck/Section.cpp:30:
/tmp/opm-parser/lib/eclipse/include/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp:27:30: fatal error: ert/ecl/Smspec.hpp: Datei oder Verzeichnis nicht gefunden
 #include <ert/ecl/Smspec.hpp>
                              ^
compilation terminated.
lib/eclipse/CMakeFiles/opmparser.dir/build.make:517: recipe for target 'lib/eclipse/CMakeFiles/opmparser.dir/Deck/Section.cpp.o' failed
make[2]: *** [lib/eclipse/CMakeFiles/opmparser.dir/Deck/Section.cpp.o] Error 1
CMakeFiles/Makefile2:3855: recipe for target 'lib/eclipse/CMakeFiles/opmparser.dir/all' failed
make[1]: *** [lib/eclipse/CMakeFiles/opmparser.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by blattms** [comment] 2017-06-06 10:23
This is really standalone, i.e. I freshly cloned it in /tmp with no other OPM module lying around. BTW there is a warning during the CMake run:
```
CMake Warning at CMakeLists.txt:144 (message):
  opm-data not found - skipping some integration tests.
```
maybe as a result some checks get deactivated?

**Comment by jokva** [comment] 2017-06-06 10:24
No, that just disables opm-data dependent tests. It obviously finds some ecl, otherwise the build would've stopped sooner.

Is this an old `ecl`? Is it installed somewhere?

**Comment by jokva** [comment] 2017-06-06 10:26
I just freshly built `ecl` and `opm-parser` with no issues. Are you sure you don't have an old install of ecl lying around?

**Comment by blattms** [comment] 2017-06-06 10:29
No there is no ert/ecl installed in a system path. grepping for ERT or ECL in CMakeCache.txt has no result.

Here is the complete output of a CMake run:
```
-- The CXX compiler identification is GNU 4.9.2
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- opm-parser version set to 2017.10 in dune.module
-- No build type specified - defaulting to 'Debug'.
-- The C compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   filesystem
--   date_time
--   system
--   unit_test_framework
--   regex
-- Checking whether the file system is case-sensitive
-- File system is case-sensitive
CMake Warning at CMakeLists.txt:144 (message):
  opm-data not found - skipping some integration tests.

-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/opm-parser-build1
```

**Comment by jokva** [comment] 2017-06-06 10:31
Let's see where `ecl` is picked up. Can you run `grep ecl_DIR CMakeCache.txt`?

**Comment by blattms** [comment] 2017-06-06 10:42
```
//The directory containing a CMake configuration file for ecl.
ecl_DIR:PATH=/home/mblatt/src/dune/opm/libecl-build
```
This must come from the most annoying part of cmake: The package configuration cache. You should have never activated this. It seems like it is/was activated for both ecl and opm-parser.
```
ls ~/.cmake/packages/
ecl  Eigen3  opm-parser
```
Like I said before, this cache gets overwritten with every CMake run and people building multiple configurations/module version will get build faiures that are hard to debug.
In any case there should be some kind of version checking implemented.

**Comment by blattms** [comment] 2017-06-06 10:47
And yes that might be an old version, The entry from May 18.

**Comment by jokva** [comment] 2017-06-06 10:48
Rebuild `ecl` and you should be fine, it should evict the old entry and insert the new one.

Once a project is configured it shouldn't look much at the cache, since paths are already set up.

**Comment by blattms** [comment] 2017-06-06 11:22
On Tue, Jun 06, 2017 at 03:48:33AM -0700, jokva wrote:
> Rebuild `ecl` and you should be fine, it should evict the old entry and insert the new one.

That it not an option as it might break other opm versions that I need
to work with. In a more perfect world ecl might be rather stable and
this might become an option, indeed. Currently it is not and at least for
opm-parser, that will always be more closely coupled with the rest of
opm, it might never be. 

> Once a project is configured it shouldn't look much at the cache,
> since paths are already set up.

We should stay with the real world here where developers need to do
clean builds at least every two weeks. Depending in what build tree
this happens, we will end up with non-matching versions from the
cache.

Let us stay with a minimal scenario: One release build and one debug
build. Already this might give a lot of trouble if I want to rebuild
only a few and not all modules, cleanly. If it does not do this
currently than this is due to the build system magic of opm-common or
dunecontrol specifying <package>_DIR directly. I have not tested this,
but my hope is that the cache is not used when finding opm-parser.

I have been in this cache hell 5 years ago and feel no need to go
there again.

**Comment by jokva** [comment] 2017-06-06 11:30
All of these were already problems with the Find-module system. If you already specify package_DIR directly, the cache won't be consulted. What has changed from before?

**Comment by dr-robertk** [comment] 2017-06-06 11:53
This can be fixed by replacing ecl with ERT in opm-output-prereqs.cmake. I suggest this whole cmake change to be reverted until a mature version has been provided and thoroughly tested.

**Comment by joakim-hove** [comment] 2017-06-06 13:01
> I suggest this whole cmake change to be reverted until a mature version has been provided and thoroughly tested.

It works on:

1. Jenkins.
2. Travis.
3. Statoil RHEL6 system.
4. My Ubuntu 16.04 box.
5. Atgeirrs Mac.
6. Andreas ubuntu 17.04 ??

So - it is not as if it is *completely broken*. You can of course choose to complain with harsh words - but we all do our best, and things would certainly progress faster if your approach and general attitude was more constructive. Your choice.

**Comment by dr-robertk** [comment] 2017-06-06 13:23
After the boost issue was fixed some other problems with libecl occurred due to some changes in the 
opm-output-prereqs.cmake. I haven't been following all the changes closely, so no idea what that could be caused by. 

> and things would certainly progress faster if your approach and general attitude was more constructive. Your choice. 

I would like to help but I don't have time for this right now. I already wasted 5 hours on that topic today and that as good as it gets. Concerning the attitude: Wasn't it @jokva who said he couldn't be bothered with this any longer? I think it's quite rude to change things in a central part of the code, even worse the build system, and then expect others to fix the fallout. To that end: not completely working == it's broken.

**Comment by atgeirr** [comment] 2017-06-06 13:37
I agree this was merged prematurely, perhaps some (if not all) problems could have been avoided with broader testing. Trouble is, I think most of us did not realize that this was a huge change until after the merge. Perhaps going forward we should be a little more "nagging" when pushing such changes, meaning that we ask others to try it and don't stop nagging about it until someone actually tries...

While tempting, I think that we need not revert this since
 - it works on Jenkins, and
 - a workaround exists (check out old version and ignore the polymer deck test failures).

That is assuming that work continues to try to solve this, and that it does not last much longer (a day or two tops). My opinion only.

**Comment by jokva** [comment] 2017-06-06 13:37
Read the thread again. I can't be bothered discussing with Andreas why copy-pasting libraries or killing the full boost dependency pre-C++17 is a bad idea. I've addressed all issues w.r.t. the build system.

**Comment by jokva** [comment] 2017-06-06 13:38
The patch was available for quite some time, and no-one reported any errors.

**Comment by atgeirr** [comment] 2017-06-06 13:43
> The patch was available for quite some time, and no-one reported any errors.

We cannot assume that all any particular patch will be tried by anybody else, unless we ask them to (which was my point above: let's do that).

**Comment by atgeirr** [comment] 2017-06-06 13:46
Because if we don't ask for involvement:

http://hitchhikersguidequotes.tumblr.com/post/14333727462/mr-prosser-but-mr-dent-the-plans-have-been

I am not saying this situation was as bad as that though! There has been no effort to *hide* it. Beware  of the build system leopard!

**Comment by blattms** [comment] 2017-06-06 14:05
Oops, this took off quite a bit (offtopic-wise). I was simply trying to be a dumb user and test opm-parser stand-alone without any manual configuration. It broke not during configure, but during building. I would have loved to get a meaningful error. I guess we can agree on the fact that it was not very easy to find the underlying issue here.

>All of these were already problems with the Find-module system. If you already specify package_DIR directly, the cache won't be consulted. What has changed from before?

Yes as long as I list everything as <package>_DIR I am safe (overriding the package registry). But I fear people will try without this, too and get bitten.  Some, like me are even as dumb as specifying ECL_DIR instead of ecl_DIR. The issue is that cmake-packages(7) says: "The search order among package registry entries for a single package is unspecified and the entry names (hashes in this example) have no meaning". This renders this a bit pointless for people not deleting their old build directories. Just try using two build directories for libecl and you will get two package registry entries.

I am not asking for any reversion of patches. I just think that this particular issue that I have could be resolved in a better way by more elaborated tests during the cmake run. And I think using the package registry is not a good idea, but this is of course my personal opinion.

**Comment by jokva** [comment] 2017-06-06 14:12
> I guess we can agree on the fact that it was not very easy to find the underlying issue here.

Well, it was reading *one* variable to figure out what was wrong, and you did not have a fresh ecl (which was my first question), so I wouldn't say it was that hard.

> But I fear people will try without this, too and get bitten.

Then they've usually either installed `ecl` or have a fairly new compilation lying about, which makes the problem go away. Most people should get away with compiling a release version of `ecl` anyway, I don't see why you'd need it in debugging mode.

**Closed** 2017-06-06 14:14 UTC
Labels: bug

**Comment by blattms** [comment] 2017-06-06 14:24
> Well, it was reading one variable to figure out what was wrong

That was 9 message for resolution. I would not like to give this support multiple times. Did you really think of the package registry?

> Then they've usually either installed ecl

How does this help? The package registry will not contain that.

**Comment by jokva** [comment] 2017-06-06 14:32
> That was 9 message for resolution. I would not like to give this support multiple times. Did you really think of the package registry?

Yep, first thing I considered, which is why I asked you if `ecl` was fresh.

> How does this help? The package registry will not contain that.

Exactly, but `find_package` prefers installed versions (it looks in "standard" locations including /usr/local and I think /opt).

**Comment by blattms** [comment] 2017-06-06 17:43
> 
> Exactly, but `find_package` prefers installed versions (it looks in "standard" locations including /usr/local and I think /opt).
> 

Which brings us back to the missing  version check. The installed version
might be older than the needed one. Sounds like an argument for
reopening to me.

**Comment by jokva** [comment] 2017-06-07 06:08
Sure, but `ecl` isn't really versioned at all, i.e. things happen in micro-esque releases that opm depend on, and those aren't tracked at all. Maybe that should be introduced, but it's certainly not a *new* issue or even related to how the package is found.
