### ISSUE TITLE
ZCORN should be nondecreasing along pillars

### ISSUE THREAD

**Issue by nairr** [OPM/opm-parser#988] opened 2016-11-22 13:48 UTC
I receive an error during initialization of one of the model 2 realizations. It is as follows:

ZCORN should be strictly nondecreasing along pillars!

ZCORN should be strictly nondecreasing along pillars!
Attempt to reverse sign in ZCORN failed.
Grid definition may be broken
Program threw an exception: [/home/opm/opm-core/opm/core/utility/SparseTable.hpp:223] Must have at least one row. Got 0 rows.

I also see that this issue should have been solved with OPM/opm-parser #238

**Comment by joakim-hove** [comment] 2016-11-22 14:03
> I also see that this issue should have been solved with OPM/opm-parser #238 

I can not see that #238 is related to this topic; but we will look into it. Which realization?

**Comment by nairr** [comment] 2016-11-22 14:10
Thanks, realization-1

**Comment by joakim-hove** [comment] 2016-11-22 14:56
OK - the problem here is that one particular cell has zero thickness along one edge:

```txt
Corner:0  degenerate in location (84,173,12)  z1:2747.35  z2:2747.35 
Corner:2  degenerate in location (84,173,12)  z1:2747.35  z2:2747.35 
```
 The exception you are seeing is raised in the grid processing code in opm-core, I think that is where the fix or workaround must come. @atgeirr?

**Comment by atgeirr** [comment] 2016-11-22 15:02
> The exception you are seeing is raised in the grid processing code in opm-core, I think that is where the fix or workaround must come

It should still be nondecreasing?!? If I can have access to the case file in question I can look at this.

**Comment by bska** [comment] 2016-11-22 15:03
> the problem here is that one particular cell has zero thickness along one edge:

That's usually not a problem at all.  The diagnostic concerning nondecreasing ZCORN considers a single pillar at a time.  This throws if "`ZCORN[p, i + k] < ZCORN[p, i]`" for some pillar `p` and corner index `k > 0`.

**Comment by joakim-hove** [comment] 2016-11-22 15:17
> It should still be nondecreasing?!?

Sorry - that was slighly wrong; the test I had in the diagnosis code was:
```C
if (z[c][1] < z[c][0])
   fprintf(stderr,"Corner: %d .... );
```
i.e. the code indicated that the values are not equal but actually decreasing.  However I do seem to be unable to coax `printf()` to output a visible difference:

```txt
Corner:2  degenerate in location (84,173,12)  z1: 2747.35400390625  z2: 2747.35302734375
Corner:2  degenerate in location (84,172,12)  z1: 2747.35400390625  z2: 2747.35302734375
```
I don't understand?

**Comment by bska** [comment] 2016-11-22 15:22
>
```
z1: 2747.35400390625
z2: 2747.35302734375
```

So `z2 < z1` (`.354` vs. `.353`).  Isn't that what the test says?

**Comment by joakim-hove** [comment] 2016-11-22 15:23
> So z2 < z1 (.354 vs. .353). Isn't that what the test says?

Yes - you are right; see updated comment.

**Comment by joakim-hove** [comment] 2016-11-22 15:38
OK: if you wish you *try* [this branch](https://github.com/joakim-hove/ert/tree/broken-cells) which manually forces the cell(s) to have zero thickness. Observe that this is **not** a fix - this branch will never be merged, but you could try it out just to get further.

**Comment by joakim-hove** [comment] 2016-11-22 23:07
Whether this is a path we at all want to follow is not clear to me, but this https://github.com/OPM/opm-parser/pull/990 should at least be *possible* approach.

**Comment by joakim-hove** [comment] 2016-11-30 16:15
#990 has been merged.

**Comment by nairr** [comment] 2016-12-02 12:30
I am still receiving the same error on model2, realization-1 after merge #990. I built all the repos from master. Should I be building ERT from the broken-cells branch?

**Comment by joakim-hove** [comment] 2016-12-02 12:32
No - you should not do anything with ert.

2. des. 2016 13:30 skrev "nairr" <notifications@github.com>:

**Comment by nairr** [comment] 2016-12-02 12:45
@joakim-hove - could you please let me know if you can reproduce the error at your side?

**Comment by joakim-hove** [comment] 2016-12-02 12:48
I will look into it again, but can not handle it before monday.

Ås I recall it - I verified that things worked when we looked at this, but I might have done something wrong then.

**Comment by joakim-hove** [comment] 2016-12-02 12:56
I will look into it again, but can not handle it before monday.

Ås I recall it - I verified that things worked when we looked at this, but I might have done something wrong then.

**Comment by joakim-hove** [comment] 2016-12-04 22:01
> could you please let me know if you can reproduce the error at your side?

I can reproduce the problem at my side, not good enough testing previously -  sorry. With #1000 it works for me.

**Comment by nairr** [comment] 2016-12-05 11:06
With the fix, it works at my side as well. Thanks!

**Comment by joakim-hove** [comment] 2016-12-07 07:28
Ok - I try to close this again. Hopefully it will remain closed now:-)

**Closed by joakim-hove** 2016-12-07 07:28 UTC
