### ISSUE TITLE
Problem with TOPS keyword

### ISSUE THREAD

**Issue by larsblatny** [OPM/opm-parser#522] opened 2015-07-20 07:25 UTC
The below applies to the SPE1CASE2.DATA file at `opm-data/spe1_new/`:

I noticed that if one only specifies the depth of the top layer in TOPS, Flow will produce the 'correct' results (the same results as Eclipse). 
If the depths of all layers are specified, Flow does not produce the correct results. 
Could there be a bug in TOPS for Flow?

**Comment by joakim-hove** [comment] 2015-07-20 08:12
>Could there be a bug in TOPS for Flow?

Certainly it could - do you base this on the final simulation results, or on a EGRID comparison?

**Comment by larsblatny** [comment] 2015-07-20 09:07
I compared all the graphs (WBHP, WGIR, WOPR, and so on) which can be produced by Flow with the corresponding graphs from Eclipse. I guess that would be the "final simulation results" (?)

**Comment by joakim-hove** [comment] 2015-07-20 11:28
> I guess that would be the "final simulation results" (?)

Yes - that is what I meant with "final simulation results". Would be very convenient for me if you still have the .EGRID files from ECLIPSE and Flow with all layers specified in TOPS - could you mail them to `joaho at statoil.com`?

**Comment by joakim-hove** [comment] 2015-07-20 16:45
I agree that graphs of summary properties like WBHP, WGIR and WOPR are all wrong, and the only specifying the top layer in the TOPS keyword seems to fix the problem, however I do not think the bug(s) is with the basic `TOPS` treatment in opm-parser. My findings so far are: [In the summary below flow results should be interpreted as flow results *with all layers specified in the TOPS keyword* - with only the top layer specified in the TOPS keyword everything seems to work.]

1. Using METRIC units instead of field units the flow results agree with eclipse.
2. When using FIELDS units there is a significant difference in the initial pressure between eclipse and flow.

Will continue looking into this. Based on these temporary findings I think that: https://github.com/OPM/opm-data/pull/53 and https://github.com/OPM/opm-data/pull/54 actually hide a real problem (with the EQUIL initialisation??) - so I would prefer those PR's to be reverted.

**Comment by larsblatny** [comment] 2015-07-21 08:41
Thank you for your comments!

**Comment by alfbr** [comment] 2015-07-21 09:16
I fail to see how reverting the PRs will help. The files are cleaner with only the top layer specified, so I believe that is how they should be anyway. However, we can make an integration test with TOPS given for all layers.

**Comment by joakim-hove** [comment] 2015-07-22 09:39
> Will continue looking into this. [...] (with the EQUIL initialisation??) 

I really do not understand this - but the EQUIL initialisation seems to be off the hook.

**Comment by GitPaean** [comment] 2015-07-22 09:51
Do you mean the problem still exists even without EQUIL initialization?

**Comment by joakim-hove** [comment] 2015-07-22 10:01
> Do you mean the problem still exists even without EQUIL initialization?

My initial findings were that pressure in the `.X0000` restart files were quite different, I therefor suspected that initialisation - however further investigations indicate that the pressure solution coming from the initialisation is equal (and correct) in both cases.

**Comment by larsblatny** [comment] 2015-07-22 11:15
I agree with the above - I don't think EQUIL is the problem: If I use PRESSURE, SWAT, SGAS and RS (as in SPE1DECK.DATA) instead of EQUIL, the problem is still there (and Eclipse will still produce the correct results with and without all layers specified in TOPS)

**Comment by andlaus** [comment] 2015-07-22 12:02
be aware that the `computeSaturation()` modifies the initial condition given by the deck if EQUIL is not used. maybe this is the thing which falls on its nose. (I still consider the grid to be the most likely root cause, though.)

**Comment by joakim-hove** [comment] 2015-07-23 14:39
I have now spent two full days on this - without really finding a solution. A summary of my findings - and a symptom fix can be found here #525. Closing this now.

**Closed by joakim-hove** 2015-07-23 14:39 UTC

**Comment by joakim-hove** [comment] 2015-07-24 08:45
A proper(?) fix here: https://github.com/OPM/opm-parser/pull/526
