### ISSUE TITLE
Package registry breaks builds of other OPM modules (was: Undefined symbols for diagnose_relperm)

### ISSUE THREAD

**Issue by blattms** [OPM/opm-parser#1085] opened 2017-06-12 09:56 UTC
Just updated OPM and cannot compile opm-core anymore:
```
Linking CXX executable bin/diagnose_relperm
CMakeFiles/diagnose_relperm.dir/examples/diagnose_relperm.cpp.o: In function `main':
diagnose_relperm.cpp:(.text.startup+0x17f): undefined reference to `Opm::ParseContext::ParseContext(std::vector<std::pair<std::string, Opm::InputError::Action>, std::allocator<std::pair<std::string, Opm::InputError::Action> > > const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/diagnose_relperm.dir/build.make:113: recipe for target 'bin/diagnose_relperm' failed
make[2]: *** [bin/diagnose_relperm] Error 1
CMakeFiles/Makefile2:329: recipe for target 'CMakeFiles/diagnose_relperm.dir/all' failed
make[1]: *** [CMakeFiles/diagnose_relperm.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by blattms** [comment] 2017-06-12 10:06
I get a similar error when trying to compile flow_ebos.

**Comment by akva2** [comment] 2017-06-12 10:16
i think you need to rebuild your opm-parser. i changed that constructor from pass by value to pass by reference, and it seems your headers and binaries are not in sync. at least i cannot reproduce on my box, and several builds on jenkins done after the change have passed (though none in opm-core, just flow_ebos).

**Comment by blattms** [comment] 2017-06-12 10:17
*grrrr* and here we go again: Seems like the package registry might have kicked in again. An outdated unrelated opm version gets chosen:
```
mblatt@loft11004:~/DUNE-test/opm-simulators/opm-parallel$ cat CMakeCache.txt | grep opm-parser_ROOT
opm-parser_ROOT:STRING=/home/mblatt/DUNE-test/opm-parser/opm-analyze
mblatt@loft11004:~/DUNE-test/opm-simulators/opm-parallel$ ls -l ~/.cmake/packages/opm-parser/
total 36
-rw-r--r-- 1 mblatt mblatt 41 Jun  6 14:11 0e598f77d119826fdec4fbb245f33e1d
-rw-r--r-- 1 mblatt mblatt 48 Jun  6 19:20 20937009162acf5223ed4e167f718916
-rw-r--r-- 1 mblatt mblatt 41 Jun  7 09:27 4be5ceca11f511db0628fe7209bbfdd7
-rw-r--r-- 1 mblatt mblatt 42 Jun  6 12:10 665f08c0414a8a95adfcbfbd33e76c17
-rw-r--r-- 1 mblatt mblatt 46 Jun  7 09:16 8d9cbcac589778f0d74e818133bf5416
-rw-r--r-- 1 mblatt mblatt 46 Jun  8 10:11 a84f0580ca8526dac18518727bd78ce8
-rw-r--r-- 1 mblatt mblatt 46 Jun  7 09:34 aeaaa29c2a873d7ba799d321b8fa1d95
-rw-r--r-- 1 mblatt mblatt 53 Jun  6 17:59 f24e214aae24b9ac8ecc73beab41c673
-rw-r--r-- 1 mblatt mblatt 47 Jun  6 13:40 f33817100137a2d9816bc8753b724466
mblatt@loft11004:~/DUNE-test/opm-simulators/opm-parallel$ for i in ~/.cmake/packages/opm-parser/*; do echo -n "$i: "; cat $i; done
/home/mblatt/.cmake/packages/opm-parser/0e598f77d119826fdec4fbb245f33e1d: /home/mblatt/DUNE-test/opm-parser/opm-o2
/home/mblatt/.cmake/packages/opm-parser/20937009162acf5223ed4e167f718916: /home/mblatt/DUNE/opm-parser/opm-parallel-debug
/home/mblatt/.cmake/packages/opm-parser/4be5ceca11f511db0628fe7209bbfdd7: /home/mblatt/DUNE-2.4/opm-parser/opm-seq
/home/mblatt/.cmake/packages/opm-parser/665f08c0414a8a95adfcbfbd33e76c17: /home/mblatt/DUNE-test/opm-parser/opm-ecl
/home/mblatt/.cmake/packages/opm-parser/8d9cbcac589778f0d74e818133bf5416: /home/mblatt/DUNE-2.4/opm-parser/opm-parallel
/home/mblatt/.cmake/packages/opm-parser/a84f0580ca8526dac18518727bd78ce8: /home/mblatt/DUNE-test/opm-parser/opm-analyze
/home/mblatt/.cmake/packages/opm-parser/aeaaa29c2a873d7ba799d321b8fa1d95: /home/mblatt/DUNE-2.5/opm-parser/opm-parallel
/home/mblatt/.cmake/packages/opm-parser/f24e214aae24b9ac8ecc73beab41c673: /home/mblatt/DUNE-test/opm-parser/opm-parallel-debug
/home/mblatt/.cmake/packages/opm-parser/f33817100137a2d9816bc8753b724466: /home/mblatt/DUNE-test/opm-parser/opm-parallel
```
I am building each module with CMake cache file and rely on OPM's intelligence on using the correct module version. Here is my cache file:
```
set(METIS_ROOT "/home/mblatt/opt" CACHE STRING "metis home")
set(PARMETIS_ROOT "/home/mblatt/opt" CACHE STRING "parmentis home")
set(ecl_DIR "/home/mblatt/opt/libecl/share/cmake/ecl" CACHE STRING "ecl home")
set(DUNE_ROOT         "/home/mblatt/DUNE-test" CACHE STRING "Path to dune")
set(USE_MPI ON         CACHE STRING "Use mpi")
set(PTSCOTCH_ROOT "/home/mblatt/opt" CACHE STRING "Path to PTSCOTCH")
set(ZOLTAN_ROOT "/home/mblatt/opt" CACHE STRING "Path to ZOLTAN")
set(BUILD_TESTING OFF CACHE BOOL "Build tests")
```

I might be repeating myself, but please stop using CMake package registry!

**Comment by blattms** [comment] 2017-06-12 10:21
@akva2 This was a clean build with all modules updated.

**Comment by blattms** [comment] 2017-06-12 10:22
Of course I can always remove the package registry manually before building...

**Comment by akva2** [comment] 2017-06-12 10:24
yup. you identified the cause yourself. it's using an old lib and new headers due to the registry.

what i do to avoid this mess is to stick (on jenkins and locally) is to stick

```cmake
set(CMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY 1 CACHE BOOL "" FORCE)
```
in the toolchains.

**Comment by blattms** [comment] 2017-06-12 10:40
@akva2 Sorry, that entry does not change anything for me.

**Comment by akva2** [comment] 2017-06-12 10:41
that's what you add to a toolchain file, not a cache file. not sure what it would do in a cache file.

**Comment by joakim-hove** [comment] 2017-06-12 10:43
I am sorry for all the problems Markus is having; we will have to find a way to configure out / disable the package registry.

**Comment by akva2** [comment] 2017-06-12 10:44
it should just be an 

```
+if(NOT UNIX)
export(opm-parser)
+endif()
```

**Comment by blattms** [comment] 2017-06-12 10:47
which will still use the existing package registration but st least not create new ones-

**Comment by joakim-hove** [comment] 2017-06-12 10:47
> it should just be an

OK - thank you;

**Comment by akva2** [comment] 2017-06-12 10:48
yes, you'd have to clean out your cache if you built during the "exporty days".

**Comment by blattms** [comment] 2017-06-12 10:54
At @jokva seems a bit right when he claimed that a recent entry into the registry overwrites previous ones. 

The problem is that if there is already a package registry entry for a build directory then this entry will not be touched (e.g. the modification time changed). On my linux system the last modified entry is taken. In my case this is opm-analyze which was added June 10. The one that should be used (opm-parallel) is discarded as it does not get updated during the build of opm-parser and appears to be older for CMake.

**Comment by joakim-hove** [comment] 2017-06-13 08:44
Closing by: https://github.com/OPM/opm-common/pull/257

**Closed by joakim-hove** 2017-06-13 08:44 UTC
Labels: bug
